shell.run 'pile.lua init'

local CraftFSEmulator = require('peak-fs/craftfs-emulator')
local MountFS         = require('peak-fs/mount-fs')
local CraftFS         = require('peak-fs/craft-fs')
local PathFS          = require('peak-fs/path-fs')
local FS              = require('peak-fs/fs')

local root = MountFS.new()
root:mount('/cc', CraftFS.new(fs))
local handle = root:open('root', '/cc/dev/fs-test.lua', 'r')
-- print(textutils.serialize({ handle:read('*l') }))
handle:close()
local emuFS = CraftFSEmulator.new(root)
local wat = CraftFS.new(emuFS.craftFS)
local circular = CraftFSEmulator.new(wat)
-- print(circular.craftFS.open('/cc/test.lua', 'r').readAll())
local realFS = PathFS.new(wat, "cc")
local handle = realFS:open('root', '/dev/fs-test.lua', 'r')
print(textutils.serialize({ handle:read('*l') }))
handle:close()